[package]
name = "wgsl_bindgen"
version = "0.5.3"
authors = ["Swoorup", "ScanMountGoat(Original)"]
description = "Generate typesafe Rust bindings for wgsl shaders in wgpu"
license = "MIT"
documentation = "https://docs.rs/wgsl_bindgen"
repository = "https://github.com/Swoorup/wgsl_bindgen"
readme = "../README.md"
edition = "2021"

[dependencies]
naga = { version = "0.19.0", features = ["wgsl-in"] }
wgpu-types = "0.19.0"
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
prettyplease = "0.2"
thiserror = "1.0"
case = "1.0"

[dev-dependencies]
indoc = "2.0"
pretty_assertions = "1.2.1"
